#!/bin/bash
#Raspberry Pi setup script
host="http://signs.pilotpen.com"
rotation=0
main () {
    if [ $(id -u) = "0" ]; then
        echo You cannot be root to run this script >&2
        exit 1
    fi

    parseParameters "$@"
    keyboard
    hostname
    reboot
    if [ $silent -ne 1 ]; then
      menu
    else
      genericSetup
    fi
    
    if [ "$rebootChoice" = "Y" ]; then
        echo "Rebooting"
        sudo reboot
    else
        if pgrep iceweasel > /dev/null; then
            wget -q http://signs.pilotpen.com/api/redirect/$(/bin/hostname -I|awk '{print $1}')/$(echo $url | awk 'BEGIN {FS="/"} {print $NF}') -O /tmp/wget-trash
        else
            (iceweasel $url --display=:0 --profile kioskProfile &) > /dev/null 2>&1
        fi
    fi
}

parseParameters() {
  silent=0
  killApache=1
  while [ "$1" != "" ]; do
    case $1 in
      -s | --silent )
        silent=1
        url=`cat /var/local/url`
        rotation=`cat /boot/config.txt | grep display_rotate | awk 'BEGIN{FS="="} {print $2}'`
        ;;
      --nokill )
        killApache=0
    esac
    shift
  done
}

keyboard() {
    sudo tee /etc/default/keyboard > /dev/null << _EOF_
# KEYBOARD CONFIGURATION FILE

# Consult the keyboard(5) manual page.

XKBMODEL="pc105"
XKBLAYOUT="us"
XKBVARIANT=""
XKBOPTIONS=""

BACKSPACE="guess"
_EOF_
}

hostname() {
    name=`cat /etc/hostname`
    echo -n "Hostname [$name]: "
    if [ $silent -ne 1 ]; then
      read newName
    fi
    if [ "$newName" != "" ] && [ "$newName" != "$name" ]; then
        echo $newName | sudo tee /etc/hostname > /dev/null
        sudo tee /etc/hosts > /dev/null << _EOF_
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1       $newName
_EOF_
    fi
}

reboot() {
    echo -n "Reboot after setup [Y]: "
    if [ $silent -ne 1 ]; then
      read rebootChoice
    else
      rebootChoice="N"
    fi
    if [ "$rebootChoice" = "" ]; then
        rebootChoice="Y"
    else
        rebootChoice="${rebootChoice^^}"
    fi
}

menu () {
    selection=0

    while [ true ]; do
        cat << _EOF_
Please select one of the following choices:
    1) Setup a single machine display
    2) Setup a schedule display
    3) Setup a lanes display
_EOF_
        read selection
        case $selection in
        1 ) 
            singleMachineDisplay
            genericSetup
            break
        ;;
        2 ) 
            scheduleDisplay
            genericSetup
            break
        ;;
        3 ) 
            lanesDisplay
            genericSetup
            break
        ;;
        * ) 
            echo "Invalid Choice"
            echo 
        esac
    done
}

genericSetup() {
    #Set TimeZone
    sudo cp /usr/share/zoneinfo/US/Eastern /etc/localtime

    command -v cec-client >/dev/null 2>&1
    hasCec=$?
    command -v iceweasel >/dev/null 2>&1
    hasIceweasel=$?
    command -v unclutter >/dev/null 2>&1
    hasUnclutter=$?
    command -v php > /dev/null 2>&1
    hasPhp=$?
    command -v omxplayer > /dev/null 2>&1
    hasOmx=$?
    apachectl -t -D DUMP_MODULES 2>&1 | grep rewrite_module > /dev/null
    hasRewriteModule=$?
    apachectl -t -D DUMP_MODULES 2>&1 | grep headers_module > /dev/null
    hasHeadersModule=$?

    allInstalled=$((hasCec == 0 && hasIceweasel == 0 && hasUnclutter == 0 && hasPhp == 0 && hasRewriteModule == 0 && hasHeadersModule == 0 && hasOmx == 0))
    
    if [ $allInstalled -ne 1 ]; then
        echo Updating apt-get
        sudo apt-get update  #&>/dev/null
        if [ $? -ne 0 ]; then
            echo Error updating apt-get. >&2
            exit 2
        fi
        echo Installing prerequisites
        sudo apt-get install -y iceweasel unclutter php5 libapache2-mod-php5 vim omxplayer 
        if [ $? -ne 0 ]; then
            echo Error installing prerequisites. >&2
            exit 3
        fi

        sudo a2enmod rewrite headers > /dev/null
        if [ $killApache -eq 1 ]; then
          sudo service apache2 restart
        fi

        if [ $hasCec -ne 0 ]; then
            cecInstall
        fi    
    fi
    
    echo Install Profile
    if [ ! -f kioskProfile.tar ]; then
        wget https://raw.githubusercontent.com/PilotCorp/RPI/master/kioskProfile.tar -q --progress=bar --show-progress
    fi
    md5=`md5sum kioskProfile.tar`
    if [ "$md5" != "67377b11c05cfd673ff357a29c6c2c59  kioskProfile.tar" ]; then
        #If profile update is required, need to kill iceweasel
        killall -q iceweasel
        wget https://raw.githubusercontent.com/PilotCorp/RPI/master/kioskProfile.tar -O kioskProfile.tar -q --progress=bar --show-progress
    fi

    if [ -d ~/kioskProfile ]; then
        rm -rf ~/kioskProfile
    fi
    mkdir ~/kioskProfile
    tar -xf kioskProfile.tar -C ~/kioskProfile
    
    echo Apache Config
    sudo wget https://raw.githubusercontent.com/PilotCorp/RPI/master/apache2.conf -O /etc/apache2/apache2.conf -q --progress=bar --show-progress
    #run apache as pi user and pi group
    sudo sed -i s/www-data/pi/g /etc/apache2/envvars
    if [ $killApache -eq 1 ]; then
      sudo service apache2 restart
    fi
    
    echo Boot Config
    sudo wget https://raw.githubusercontent.com/PilotCorp/RPI/master/config.txt -O /boot/config.txt -q --progress=bar --show-progress

    echo Video Player script
    wget https://raw.githubusercontent.com/PilotCorp/RPI/master/videoplayer -O /home/pi/videoplayer -q --progress=bar --show-progress
    chmod 755 /home/pi/videoplayer

    echo Grabbing Videos
    wget https://raw.githubusercontent.com/PilotCorp/RPI/master/DownloadVideos.php -O DownloadVideos.php -q --progress=bar --show-progress
    php DownloadVideos.php

    echo Setting Rotation
    echo | sudo tee -a /boot/config.txt > /dev/null
    echo "#Setting Roation" | sudo tee -a /boot/config.txt > /dev/null
    echo "display_rotate="$rotation | sudo tee -a /boot/config.txt > /dev/null
    
    echo Configuring autostart
    sudo wget https://raw.githubusercontent.com/PilotCorp/RPI/master/rc.local -O /etc/rc.local -q --progress=bar --show-progress

    tee ~/.config/lxsession/LXDE-pi/autostart  > /dev/null << _EOF_
@lxpanel --profile LXDE-pi
@pcmanfm --desktop --profile LXDE-pi
@xscreensaver -no-splash
@xset s noblank
@xset s off
@xset -dpms
apt-get install iceweasel
apt-get install unclutter
unclutter -display :0 -noevents -grab
/home/pi/setup --silent
_EOF_

   echo $url | sudo tee /var/local/url > /dev/null 

   echo Installing Website
   webSite
}

webSite() {
    wget https://github.com/PilotCorp/ManufacturingSignsHostedHtml/archive/master.zip -O ManufacturingSignsHostedHtml.zip -q --progress=bar --show-progress
    sudo unzip -ju ManufacturingSignsHostedHtml.zip ManufacturingSignsHostedHtml-master/* -d /var/www/html > /dev/null
}

cecInstall() {
    echo Installing cec-client
    #https://github.com/Pulse-Eight/libcec
    sudo apt-get install -y cmake liblockdev1-dev libudev-dev libxrandr-dev python-dev swig
    cd
    git clone https://github.com/Pulse-Eight/platform.git
    mkdir platform/build
    cd platform/build
    cmake ..
    make
    sudo make install
    cd
    git clone https://github.com/Pulse-Eight/libcec.git
    mkdir libcec/build
    cd libcec/build
    cmake -DRPI_INCLUDE_DIR=/opt/vc/include -DRPI_LIB_DIR=/opt/vc/lib ..
    make -j4
    sudo make install
    sudo ldconfig
}

singleMachineDisplay () {
    echo ------------------------ SINGLE MACHINE DISPLAY SETUP -------------------------
    echo -n "Enter the two character machine code: "
    read machine
    url="$host/${machine^^}"
}

scheduleDisplay () {
    echo --------------------------- SCHEDULE DISPLAY SETUP ----------------------------
    save=
    until [ "${save^^}" = "S" ]; do
        machines=""
        echo Enter the machine codes for the machines to display
        echo Hit enter after each, a blank line will stop input
        read machine
        until [ "$machine" = "" ]; do
            machines="$machines$machine,"
            read machine
        done
        echo "You have entered \"${machines^^}\""
        echo -n "Would you like to save this (S) or re-enter (R) choices [S]: "
        read save
        if [ "$save" = "" ]; then 
            save="S" 
        fi
    done
    pickRotation 
    url="$host/${machines^^}"
}

lanesDisplay () {
    echo ---------------------------- LANES DISPLAY SETUP ------------------------------
    url="$host/Lanes"
}

pickRotation () {
  while [ true ]; do
    cat << _EOF_
Please select one of the following screen rotations:
    0  ) Normal landscape
    90 ) 90 degrees counter-clockwise, portait
    180) Upside down landscape
    270) 270 degress counter-clockwise/90degress clockwise, portait
_EOF_
    read selection
    case $selection in
    0 )
        rotation=0
        break
    ;;
    90 )
        rotation=1
        break
    ;;
    180 )
        rotation=2
        break
    ;;
    270 )
        rotation=3
        break
    ;;
    * )
        echo "Invalid Choice"
        echo
    esac
  done
}

#Actually run the main function
main "$@"
