#!/bin/bash
#Raspberry Pi setup script

echo "Auto Update"
wget https://raw.githubusercontent.com/PilotCorp/RPI/master/setup -O setup > /dev/null 2>&1
wget signs.pilotpen.com/script -O script > /dev/null 2>&1
chmod 755 script
./script

