#!/bin/bash
#Raspberry Pi setup script

echo "Auto Update"
wget https://raw.githubusercontent.com/PilotCorp/RPI/master/setup -q --progress=bar --show-progress -O setup

wget https://raw.githubusercontent.com/PilotCorp/RPI/master/script -q --progress=bar --show-progress -O script

chmod 755 script
./script "$@"

