#!/bin/sh

ps aux | grep omxplayer | grep -v grep > /dev/null
if [ $? -eq 0 ]; then #omxplayer already active
  exit 0
fi

# get rid of the cursor so we don't see it when videos are running
setterm -cursor off

# set here the path to the directory containing your videos
VIDEOPATH="/home/pi/Videos"

# you can normally leave this alone
SERVICE="omxplayer"

# now for our infinite loop!
while true; do
    for entry in $VIDEOPATH/*
    do
        omxplayer -o hdmi "$entry" > /dev/null
    done
done

